import React, { useMemo } from 'react';
import { useSheet } from '../context/SheetContext';
import { calculateLayout } from '../utils/layoutEngine';
import 'katex/dist/katex.min.css';
import { InlineMath, BlockMath } from 'react-katex';

const ModuleItem = ({ item }) => {
    return (
        <div className="mb-2 text-[10px] border border-slate-200 rounded p-1.5 break-inside-avoid">
            <div className="font-bold text-slate-700 border-b border-slate-100 pb-0.5 mb-1 flex justify-between">
                <span>{item.title}</span>
                <span className="text-[8px] text-slate-400 font-normal truncate max-w-[50px]">{item.parentTitle}</span>
            </div>

            <div className="module-content overflow-hidden">
                {item.type === 'text' && (
                    <div className="whitespace-pre-wrap font-serif leading-tight text-slate-800">
                        {item.content}
                    </div>
                )}

                {item.type === 'image' && (
                    <div className="flex justify-center">
                        <img src={item.src} className="max-h-[150px] object-contain rounded" />
                    </div>
                )}

                {item.type === 'formula' && (
                    <div className="text-center my-1">
                        <InlineMath math={item.content} />
                    </div>
                )}

                {item.type === 'code' && (
                    <div className="bg-slate-50 p-1 rounded font-mono text-[9px] whitespace-pre overflow-x-auto">
                        {item.content}
                    </div>
                )}
            </div>
        </div>
    )
}

const A4Page = ({ pageNumber, columns }) => {
    return (
        <div id={`page-${pageNumber}`} className="bg-white w-[210mm] h-[297mm] shadow-2xl relative mx-auto mb-8 transition-all duration-300 origin-top flex flex-col overflow-hidden group print:shadow-none print:mb-0 print:w-full print:h-full">
            {/* Helper Grid Overlay (Hover only) */}
            <div className="absolute inset-0 pointer-events-none border border-red-500/0 group-hover:border-red-500/20 transition-colors z-50 print:hidden" />

            {/* Page Content */}
            <div className="flex-1 p-[5mm] text-slate-900">
                <h3 className="font-bold text-sm mb-2 text-center border-b-2 border-slate-800 pb-1 uppercase tracking-widest">
                    CSEN701 Cheatsheet <span className="text-slate-400 mx-2">//</span> Page {pageNumber}
                </h3>

                <div className="grid grid-cols-2 gap-3 h-full items-start">
                    {/* Column 1 */}
                    <div className="h-full flex flex-col">
                        {columns[0].map((item, i) => (
                            <ModuleItem key={`${item.id}-col1-${i}`} item={item} />
                        ))}
                    </div>

                    {/* Column 2 */}
                    <div className="h-full flex flex-col">
                        {columns[1].map((item, i) => (
                            <ModuleItem key={`${item.id}-col2-${i}`} item={item} />
                        ))}
                    </div>
                </div>
            </div>

            {/* Footer */}
            <div className="absolute bottom-2 right-4 text-[8px] text-slate-400 font-mono">
                Generated by SheetOnTheGo • Page {pageNumber}
            </div>
        </div>
    );
};

const SheetPreview = () => {
    const { modules, selectedItems, weights } = useSheet();

    const { pages, overflow } = useMemo(() => {
        return calculateLayout(modules, selectedItems, weights);
    }, [modules, selectedItems, weights]);

    // Handle Print
    const handlePrint = () => {
        window.print();
    };

    return (
        <main className="ml-80 flex-1 min-h-screen bg-slate-950 p-8 overflow-y-auto print:ml-0 print:p-0 print:overflow-visible">
            <div className="max-w-[220mm] mx-auto print:max-w-none print:w-full print:mx-0">
                <div className="flex justify-between items-center mb-6 print:hidden">
                    <div>
                        <h1 className="text-2xl font-bold text-white">Live Preview</h1>
                        {overflow.length > 0 && (
                            <div className="text-red-400 text-sm mt-1 flex items-center gap-1 animate-pulse">
                                ⚠️ {overflow.length} items overflowing! Decrease weights or remove items.
                            </div>
                        )}
                    </div>
                    <div className="flex gap-2">
                        <button
                            onClick={handlePrint}
                            className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-sm font-medium transition-colors shadow-lg shadow-blue-900/20 flex items-center gap-2"
                        >
                            Print / Save PDF
                        </button>
                    </div>
                </div>

                <div className="print-area">
                    {/* Page 1 */}
                    <A4Page pageNumber={1} columns={pages[0].columns} />

                    {/* Page 2 */}
                    <A4Page pageNumber={2} columns={pages[1].columns} />
                </div>
            </div>
        </main>
    );
};

export default SheetPreview;
